---
title: "qPCR analysis"
author: "Harriet"
date: "2023-01-26"
output: html_document
---

This script allows qPCR data statistical analysis and plotting. Data used in this script is relative expression ratios(Pfaffl method), calculated as described : https://toptipbio.com/pfaffl-method-qpcr/
Using an average of control samples (=water treated) as a calibrator. Primer efficiency was calculated and used in the equations. 

Load libraries
```{r}
library(tidyverse)
library(rstatix)  
library(here)
```

```{r}
my_data <- read.table(here("data", "variovorax.txt"), sep = "\t", header = T)

#Identify outliers
#pri.miR159c
identify_outliers(my_data[my_data$Treatment == "miPEP",], variable="pri.miR159c") #None
identify_outliers(my_data[my_data$Treatment == "scrambled",], variable="pri.miR159c") #4.176437, row 18
identify_outliers(my_data[my_data$Treatment == "water",], variable="pri.miR159c")# None

#Phosphatidate.cytydylytransferase
identify_outliers(my_data[my_data$Treatment == "miPEP",], variable="Phosphatidate.cytidylyltransferase") #None
identify_outliers(my_data[my_data$Treatment == "scrambled",], variable="Phosphatidate.cytidylyltransferase") #None
identify_outliers(my_data[my_data$Treatment == "water",], variable="Phosphatidate.cytidylyltransferase")# None

#alpha.2.macroglobulin
identify_outliers(my_data[my_data$Treatment == "miPEP",], variable="alpha.2.macroglobulin") #None
identify_outliers(my_data[my_data$Treatment == "scrambled",], variable="alpha.2.macroglobulin") #None
identify_outliers(my_data[my_data$Treatment == "water",], variable="alpha.2.macroglobulin")# None

#LysR
identify_outliers(my_data[my_data$Treatment == "miPEP",], variable="LysR") #0.646076, row 1
identify_outliers(my_data[my_data$Treatment == "scrambled",], variable="LysR") #None
identify_outliers(my_data[my_data$Treatment == "water",], variable="LysR")# None

#Remove outliers
my_data[8,2] <- NA
my_data[1,5] <- NA

#Make long for plotting
data_long<- gather(my_data, Gene, Ratio, 2:5)
#Order the different genes
data_long$Gene <- factor(data_long$Gene, c("pri.miR159c", "Phosphatidate.cytidylyltransferase", "alpha.2.macroglobulin", "LysR"))
data_long$Treatment <- factor(data_long$Treatment, c("water", "miPEP", "scrambled"))

#To have correct label names
gene.labs <- c("pri-miR159c", "Alpha-2-macroglobulin","CdsA", "LysR")
names(gene.labs) <- c("pri.miR159c",  "alpha.2.macroglobulin", "Phosphatidate.cytidylyltransferase","LysR")
 
plot <- ggplot(data_long[data_long$Treatment!="scrambled",],aes(x =Treatment, y = Ratio))+
  geom_boxplot() +
  geom_point() +
  theme_bw() +
  facet_wrap(~Gene, nrow = 2, ncol =2, scales = "free_y", labeller = labeller(Gene = gene.labs))
  
plot

ggsave(here("output", "Fig1.tiff"), plot, width=7, height=7, compression = "lzw", units="in")

```

###### Statistical analysis ######

```{r}
shapiro.test(data_long[data_long$Gene=="pri.miR159c",3]) #P=0.1211
shapiro.test(log(data_long[data_long$Gene=="LysR",3])) #P=0.1229
shapiro.test(data_long[data_long$Gene=="alpha.2.macroglobulin",3]) #P=0.9153
shapiro.test(log(data_long[data_long$Gene=="Phosphatidate.cytidylyltransferase",3])) #P=0.7232

#T-test between water and miPEP
t.test(data_long[data_long$Gene=="pri.miR159c" & data_long$Treatment=="water",3], 
    data_long[data_long$Gene=="pri.miR159c" & data_long$Treatment=="miPEP",3]) #t=-3.3791, P=0.009722
t.test(log(data_long[data_long$Gene=="Phosphatidate.cytidylyltransferase" & data_long$Treatment=="water",3]), 
    log(data_long[data_long$Gene=="Phosphatidate.cytidylyltransferase" & data_long$Treatment=="miPEP",3])) #t=3.4297, P=0.006474
t.test(data_long[data_long$Gene=="alpha.2.macroglobulin" & data_long$Treatment=="water",3], 
    data_long[data_long$Gene=="alpha.2.macroglobulin" & data_long$Treatment=="miPEP",3]) #t=-2.92, P=0.04621
t.test(log(data_long[data_long$Gene=="LysR" & data_long$Treatment=="water",3]), 
    log(data_long[data_long$Gene=="LysR" & data_long$Treatment=="miPEP",3])) #t=4.2681, P=0.005365

#T-test between water and scrambled
t.test(data_long[data_long$Gene=="pri.miR159c" & data_long$Treatment=="water",3], 
    data_long[data_long$Gene=="pri.miR159c" & data_long$Treatment=="scrambled",3]) #t=-0.86029, P=0.4184
t.test(log(data_long[data_long$Gene=="Phosphatidate.cytidylyltransferase" & data_long$Treatment=="water",3]), 
    log(data_long[data_long$Gene=="Phosphatidate.cytidylyltransferase" & data_long$Treatment=="scrambled",3])) #t=0.66799, P=0.5246
t.test(data_long[data_long$Gene=="alpha.2.macroglobulin" & data_long$Treatment=="water",3], 
    data_long[data_long$Gene=="alpha.2.macroglobulin" & data_long$Treatment=="scrambled",3]) #t=0.17628, P=0.8634
t.test(log(data_long[data_long$Gene=="LysR" & data_long$Treatment=="water",3]), 
    log(data_long[data_long$Gene=="LysR" & data_long$Treatment=="scrambled",3])) #t=0.17075, P=0.8676

```